//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE_DETAILS
    {
        public decimal ATTENDANCE_ID { get; set; }
        public decimal CLASS_ID { get; set; }
        public decimal STUDENT_ID { get; set; }
        public System.DateTime ATTENDANCE_DATE { get; set; }
    
        public virtual CLASS_DETAILS CLASS_DETAILS { get; set; }
        public virtual STUDENT_DETAILS STUDENT_DETAILS { get; set; }
    }
}
