//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASS_DETAILS()
        {
            this.ATTENDANCE_DETAILS = new HashSet<ATTENDANCE_DETAILS>();
            this.STUDENT_DETAILS = new HashSet<STUDENT_DETAILS>();
        }
    
        public decimal CLASS_ID { get; set; }
        public decimal CLASS_LEVEL_ID { get; set; }
        public string CLASS_NAME { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public byte MONDAY { get; set; }
        public byte TUESDAY { get; set; }
        public byte WEDNESDAY { get; set; }
        public byte THURSDAY { get; set; }
        public byte FRIDAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE_DETAILS> ATTENDANCE_DETAILS { get; set; }
        public virtual CLASS_LEVEL CLASS_LEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_DETAILS> STUDENT_DETAILS { get; set; }
    }
}
