//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KungFuDBEntities2 : DbContext
    {
        public KungFuDBEntities2()
            : base("name=KungFuDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS_LEVEL> CLASS_LEVEL { get; set; }
        public virtual DbSet<PROGRESS_DETAILS> PROGRESS_DETAILS { get; set; }
        public virtual DbSet<RANK_DETAILS> RANK_DETAILS { get; set; }
        public virtual DbSet<PAYMENT_DETAILS> PAYMENT_DETAILS { get; set; }
        public virtual DbSet<PRODUCT_DETAILS> PRODUCT_DETAILS { get; set; }
        public virtual DbSet<STUDENT_DETAILS> STUDENT_DETAILS { get; set; }
        public virtual DbSet<ATTENDANCE_DETAILS> ATTENDANCE_DETAILS { get; set; }
        public virtual DbSet<CLASS_DETAILS> CLASS_DETAILS { get; set; }
    }
}
