//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_DETAILS
    {
        public decimal PAYMENT_ID { get; set; }
        public decimal STUDENT_ID { get; set; }
        public Nullable<decimal> PRODUCT_ID { get; set; }
        public decimal MONEY_RECEIVED { get; set; }
        public System.DateTime DATE_RECEIVED { get; set; }
    
        public virtual PRODUCT_DETAILS PRODUCT_DETAILS { get; set; }
        public virtual STUDENT_DETAILS STUDENT_DETAILS { get; set; }
    }
}
