//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRESS_DETAILS
    {
        public decimal PROGRESS_ID { get; set; }
        public decimal STUDENT_ID { get; set; }
        public decimal RANK_ID { get; set; }
        public System.DateTime AWARDED_DATE { get; set; }
    
        public virtual RANK_DETAILS RANK_DETAILS { get; set; }
        public virtual STUDENT_DETAILS STUDENT_DETAILS { get; set; }
    }
}
