//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_DETAILS()
        {
            this.PAYMENT_DETAILS = new HashSet<PAYMENT_DETAILS>();
            this.PROGRESS_DETAILS = new HashSet<PROGRESS_DETAILS>();
            this.ATTENDANCE_DETAILS = new HashSet<ATTENDANCE_DETAILS>();
        }
    
        public decimal STUDENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DATE_OF_JOINING { get; set; }
        public decimal CONTACT_NUM { get; set; }
        public string EMAIL_ID { get; set; }
        public string STREET_ADDRESS { get; set; }
        public string STREET_ADDRESS_2 { get; set; }
        public string POSTAL_CODE { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public decimal RANK_ID { get; set; }
        public byte ACTIVE { get; set; }
        public string MOTHER_NAME { get; set; }
        public string MOTHER_MOBILE_NO { get; set; }
        public string MOTHER_EMAIL_ID { get; set; }
        public string FATHER_NAME { get; set; }
        public string FATHER_MOBILE_NO { get; set; }
        public string FATHER_EMAIL_ID { get; set; }
        public byte IS_PARENT { get; set; }
        public Nullable<decimal> CHILD_ID { get; set; }
        public Nullable<decimal> BELT_NAME { get; set; }
        public Nullable<decimal> CLASS_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT_DETAILS> PAYMENT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRESS_DETAILS> PROGRESS_DETAILS { get; set; }
        public virtual RANK_DETAILS RANK_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE_DETAILS> ATTENDANCE_DETAILS { get; set; }
        public virtual CLASS_DETAILS CLASS_DETAILS { get; set; }
    }
}
